name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install libpcap-dev
      run: sudo apt-get install -y libpcap-dev
    
    - name: build
      run: ./build.sh
